<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AgentUp.CLI\AgentUp.CLI.csproj" />
    <ProjectReference Include="..\AgentUp.Desktop\AgentUp.Desktop.csproj" />
    <ProjectReference Include="..\AgentUp.InstallerConfig\AgentUp.InstallerConfig.csproj" />
    <ProjectReference Include="..\AgentUp.Server\AgentUp.Server.csproj" />
    <ProjectReference Include="..\AgentUp.Tray\AgentUp.Tray.csproj" />
    <ProjectReference Include="..\LocalInstaller.App\LocalInstaller.App.csproj" />
  </ItemGroup>

</Project>
