/**
 * The icon set, parsed from its one declaration and emitted for every surface.
 *
 * `src/icons.html` holds the geometry. This turns it into the three forms the surfaces can
 * consume - inline SVG for HTML, a StreamGeometry string for Avalonia, and a path list for
 * react-native-svg - so a Desktop glyph, a Mobile Ionicon and a catalog drawing stop being
 * three independent decisions.
 */

const iconPattern = () => /<svg\s+([^>]*)>([\s\S]*?)<\/svg>/g;
const viewBox = 24;

export function parseIcons(html) {
  const icons = [];
  const pattern = iconPattern();
  let match;
  while ((match = pattern.exec(html))) {
    const id = attr(match[1], 'icon');
    if (!id) continue;
    const geometry = match[2].replace(/\s+/g, ' ').trim();
    if (!geometry) throw new Error(`Icon '${id}' has no geometry.`);
    if (icons.some(icon => icon.id === id)) throw new Error(`Icon '${id}' is declared twice.`);
    icons.push({
      id,
      title: required(match[1], 'title', id),
      note: required(match[1], 'note', id),
      geometry,
      paths: pathData(id, geometry),
    });
  }
  if (!icons.length) throw new Error('No icons were declared.');
  return icons;
}

/** Inline SVG for HTML, with the class the catalog paints it through. */
export function iconSvg(icon, className = 'au-nav-icon') {
  return `<svg class="${className}" viewBox="0 0 ${viewBox} ${viewBox}" aria-hidden="true">${icon.geometry}</svg>`;
}

/**
 * Replaces `<span data-au-icon="menu"></span>` with the declared drawing.
 *
 * The hamburger was written out five times across the chrome and the mobile bars; referring to
 * it by name means the geometry exists once and a change to it reaches every use.
 */
export function expandIcons(html, icons) {
  const index = new Map(icons.map(icon => [icon.id, icon]));
  return html.replace(
    /<(span|i)([^>]*?)\sdata-au-icon="([^"]+)"([^>]*)>\s*<\/\1>/gi,
    (full, tag, before, id, after) => {
      const icon = index.get(id);
      if (!icon) throw new Error(`Unknown icon '${id}'. Declared: ${[...index.keys()].join(', ')}.`);
      const className = attr(`${before}${after}`, 'icon-class') || 'au-nav-icon';
      return iconSvg(icon, className);
    });
}

/**
 * Avalonia path markup.
 *
 * Avalonia's StreamGeometry takes the same subset of SVG path data, so a `path` is carried
 * across unchanged and a `rect` or `circle` is converted to one. Desktop draws icons as
 * Unicode glyphs in TextBlocks today; this is what it needs to stop.
 */
export function emitAvaloniaIcons(icons) {
  const entries = icons
    .map(icon => `    { "${icon.id}", "${icon.paths.join(' ')}" },`)
    .join('\n');
  return `// <auto-generated />
// Generated from src/icons.html by scripts/build.mjs. Do not edit.
using System.Collections.Generic;

namespace AgentUp.Desktop.Shared.Models;

/// <summary>
/// Icon geometry on a ${viewBox}x${viewBox} grid, for <c>StreamGeometry.Parse</c>. Stroke the
/// path with the surrounding text brush; do not fill it.
/// </summary>
internal static class AgentUpIcons
{
    internal const double ViewBoxSize = ${viewBox};

    internal static readonly IReadOnlyDictionary<string, string> Geometry = new Dictionary<string, string>
    {
${entries}
    };
}
`;
}

/** react-native-svg path data, for Mobile to draw instead of naming an Ionicon. */
export function emitNativeIcons(icons) {
  const entries = icons
    .map(icon => `  ${JSON.stringify(icon.id)}: Object.freeze(${JSON.stringify(icon.paths)}),`)
    .join('\n');
  return `// Generated from src/icons.html by scripts/build.mjs. Do not edit.
export const agentUpIconViewBox = ${viewBox};

/**
 * Path data on a ${viewBox}x${viewBox} grid. Render with react-native-svg, stroking with the
 * surrounding text colour rather than filling.
 */
export const agentUpIcons = Object.freeze({
${entries}
});
`;
}

export function emitNativeIconTypes(icons) {
  const union = icons.map(icon => `'${icon.id}'`).join(' | ');
  return `// Generated from src/icons.html by scripts/build.mjs. Do not edit.
export declare const agentUpIconViewBox: number;
export type AgentUpIconName = ${union};
export declare const agentUpIcons: Readonly<Record<AgentUpIconName, readonly string[]>>;
`;
}

/**
 * Path data for one icon, with the primitives Avalonia and react-native-svg cannot take
 * converted. A rounded rect becomes an explicit arc-cornered path and a circle becomes two
 * arcs, so a surface only ever has to understand `path`.
 */
function pathData(id, geometry) {
  const paths = [];
  for (const match of geometry.matchAll(/<(path|rect|circle)\s+([^>]*?)\/?>/g)) {
    const [, element, attributes] = match;
    if (element === 'path') {
      paths.push(attr(attributes, null, 'd') ?? fail(id, 'a path without d'));
      continue;
    }
    if (element === 'rect') {
      paths.push(roundedRect(id, attributes));
      continue;
    }
    paths.push(circle(id, attributes));
  }
  if (!paths.length) fail(id, 'no drawable primitive');
  return paths;
}

function roundedRect(id, attributes) {
  const x = number(id, attributes, 'x');
  const y = number(id, attributes, 'y');
  const width = number(id, attributes, 'width');
  const height = number(id, attributes, 'height');
  const radius = Number(attr(attributes, null, 'rx') ?? 0);
  if (radius <= 0) {
    return `M ${x} ${y} H ${x + width} V ${y + height} H ${x} Z`;
  }
  return `M ${x + radius} ${y} H ${x + width - radius}`
    + ` A ${radius} ${radius} 0 0 1 ${x + width} ${y + radius}`
    + ` V ${y + height - radius}`
    + ` A ${radius} ${radius} 0 0 1 ${x + width - radius} ${y + height}`
    + ` H ${x + radius}`
    + ` A ${radius} ${radius} 0 0 1 ${x} ${y + height - radius}`
    + ` V ${y + radius}`
    + ` A ${radius} ${radius} 0 0 1 ${x + radius} ${y} Z`;
}

function circle(id, attributes) {
  const cx = number(id, attributes, 'cx');
  const cy = number(id, attributes, 'cy');
  const r = number(id, attributes, 'r');
  return `M ${cx - r} ${cy} A ${r} ${r} 0 1 0 ${cx + r} ${cy} A ${r} ${r} 0 1 0 ${cx - r} ${cy} Z`;
}

function number(id, attributes, name) {
  const raw = attr(attributes, null, name);
  if (raw === null) fail(id, `a shape without ${name}`);
  const value = Number(raw);
  if (!Number.isFinite(value)) fail(id, `a non-numeric ${name}`);
  return value;
}

function fail(id, what) {
  throw new Error(`Icon '${id}' has ${what}.`);
}

function required(attributes, name, id) {
  const value = attr(attributes, name);
  if (!value) throw new Error(`Icon '${id}' has no data-au-${name}.`);
  return value;
}

function attr(raw, auName, plainName = null) {
  const name = auName ? `data-au-${auName}` : plainName;
  const match = raw.match(new RegExp(`\\b${name}="([^"]*)"`));
  return match ? match[1] : null;
}
