/**
 * Scene sequences: an ordered list of states a scene moves through.
 *
 * A scene was one still. Marketing frames and clips need the same screen at several moments,
 * and before components took a state that meant a second scene with a second copy of the
 * markup - so a transition was a DOM swap and nothing could tween.
 *
 * A step names a component, the state to put it in, and how long to hold it:
 *
 *   data-au-sequence="workspace-tabs=selected:0@900; workspace-tabs=selected:2@1400"
 *
 * Each step is resolved here into a precomputed class mutation, so a player needs no resolver
 * and the DOM never changes shape: the same elements keep their identity and only a modifier
 * class moves, which is what lets CSS transition between frames.
 */

import { parseStateDeclarations, parseStateRequest } from './states.mjs';

const defaultHoldMs = 1200;

export function parseSequence(raw) {
  const steps = [];
  for (const entry of (raw ?? '').split(';').map(value => value.trim()).filter(Boolean)) {
    const at = entry.lastIndexOf('@');
    const body = at < 0 ? entry : entry.slice(0, at);
    const hold = at < 0 ? defaultHoldMs : Number(entry.slice(at + 1));
    if (!Number.isInteger(hold) || hold <= 0) throw new Error(`Sequence step '${entry}' needs a positive hold in milliseconds.`);
    const split = body.indexOf('=');
    if (split < 1) throw new Error(`Sequence step '${entry}' is not '<component>=<state>@<hold>'.`);
    steps.push({ component: body.slice(0, split).trim(), state: body.slice(split + 1).trim(), hold });
  }
  return steps;
}

export function buildSequence(scene, raw, components) {
  const steps = parseSequence(raw);
  if (!steps.length) return [];
  return steps.map(step => {
    if (!scene.components.includes(step.component)) {
      throw new Error(`${scene.id} sequences '${step.component}', which the scene does not use.`);
    }
    const component = components.get(step.component);
    const declarations = parseStateDeclarations(component.states);
    const request = parseStateRequest(step.state);
    if (request.size !== 1) throw new Error(`${scene.id} sequence step '${step.state}' must set exactly one state.`);
    const [name, value] = [...request][0];
    const declaration = declarations.get(name);
    if (!declaration) {
      throw new Error(`${scene.id} sequences state '${name}', which ${step.component} does not declare.`);
    }
    return {
      component: step.component,
      state: step.state,
      hold: step.hold,
      apply: declaration.kind === 'selection'
        ? { kind: 'selection', member: declaration.member, modifier: declaration.modifier, index: value }
        : { kind: 'flag', modifier: declaration.modifier, on: value === true },
    };
  });
}

/**
 * The player, emitted beside the manifest.
 *
 * It only ever adds and removes a class, so a page that wants the transition animated gives
 * the member class a CSS transition and gets it for free; a frame grabber instead steps the
 * sequence itself and screenshots between calls.
 */
export function emitSequencePlayer() {
  return `// Generated by scripts/build.mjs. Do not edit.
/**
 * Drives an assembled scene through its sequence by moving modifier classes. It holds no state
 * of its own beyond the step index, talks to no Server, and never replaces an element, so the
 * DOM identity a CSS transition needs survives every frame.
 */
export function applySequenceStep(root, step) {
  if (!root || !step) return;
  const apply = step.apply;
  if (apply.kind === 'flag') {
    root.classList.toggle(apply.modifier, apply.on);
    return;
  }
  const members = [...root.querySelectorAll('.' + apply.member)];
  members.forEach((member, index) => {
    const selected = index === apply.index;
    member.classList.toggle(apply.modifier, selected);
    for (const name of ['aria-selected', 'aria-pressed', 'aria-current']) {
      if (member.hasAttribute(name)) member.setAttribute(name, selected ? 'true' : 'false');
    }
  });
}

/**
 * Steps a scene for a frame grabber: call it with each index in turn and screenshot between
 * calls. Returns the hold the step asked for, so a renderer can spread frames over real time.
 */
export function seekSequence(root, sequence, index) {
  const step = sequence[index];
  applySequenceStep(root, step);
  return step ? step.hold : 0;
}

/**
 * Plays a scene in a browser. Returns a stop function. Honours reduced motion by holding the
 * first frame, because an auto-playing product animation is motion the viewer did not ask for.
 */
export function playSequence(root, sequence, options) {
  const settings = options || {};
  const schedule = settings.setTimeout || globalThis.setTimeout;
  const cancel = settings.clearTimeout || globalThis.clearTimeout;
  const reduced = settings.reducedMotion
    ?? globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches
    ?? false;
  if (!sequence.length) return () => {};
  applySequenceStep(root, sequence[0]);
  if (reduced) return () => {};
  let index = 0;
  let timer = null;
  const tick = () => {
    index = (index + 1) % sequence.length;
    applySequenceStep(root, sequence[index]);
    timer = schedule(tick, sequence[index].hold);
  };
  timer = schedule(tick, sequence[0].hold);
  return () => {
    if (timer !== null) cancel(timer);
  };
}
`;
}

export function emitSequencePlayerTypes() {
  return `// Generated by scripts/build.mjs. Do not edit.
export type AgentUpSequenceApply =
  | { kind: 'selection'; member: string; modifier: string; index: number }
  | { kind: 'flag'; modifier: string; on: boolean };

export interface AgentUpSequenceStep {
  component: string;
  state: string;
  hold: number;
  apply: AgentUpSequenceApply;
}

export interface AgentUpSequenceOptions {
  reducedMotion?: boolean;
  setTimeout?: typeof globalThis.setTimeout;
  clearTimeout?: typeof globalThis.clearTimeout;
}

export declare function applySequenceStep(root: Element, step: AgentUpSequenceStep): void;
export declare function seekSequence(root: Element, sequence: AgentUpSequenceStep[], index: number): number;
export declare function playSequence(
  root: Element,
  sequence: AgentUpSequenceStep[],
  options?: AgentUpSequenceOptions,
): () => void;
`;
}
