apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-up-capabilities
  namespace: {{ .Values.namespace }}
data:
  capabilities.json: |
    {{- $entries := list }}
    {{- range $id, $capability := .Values.capabilities }}
    {{- if not $capability.disabled }}
    {{- $entries = append $entries (dict "id" $id "versions" ($capability.versions | default list)) }}
    {{- end }}
    {{- end }}
    {{- $entries | toPrettyJson | nindent 4 }}
