apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-up-capabilities
  namespace: {{ .Values.namespace }}
data:
  enabled.json: |
    {
      "schemaVersion": "1",
      "modules": {{ .Values.capabilities.enabled | default list | toJson }}
    }
