{{- if not .Values.server.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: agent-up-server-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  AGENTUP_ADMIN_PASSWORD: {{ required "server admin password is required" .Values.server.adminPassword | quote }}
{{- end }}
