import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');
const css = await readFile(resolve(root, 'src/agent-up.css'), 'utf8');
const marketing = await readFile(resolve(root, 'src/marketing.css'), 'utf8');
const properties = Object.fromEntries(
  [...css.matchAll(/^\s*--au-([a-z0-9-]+):\s*([^;]+);/gm)].map(([, name, value]) => [name, value.trim()]),
);

const required = [
  'color-canvas', 'color-surface', 'color-border-subtle', 'color-text-primary',
  'color-accent', 'color-status-healthy', 'color-status-danger', 'color-focus',
  'space-1', 'space-4', 'radius-md', 'control-height',
];
for (const name of required) {
  if (!properties[name]) throw new Error(`Missing canonical CSS property --au-${name}.`);
}

const camel = value => value.replace(/-([a-z0-9])/g, (_, character) => character.toUpperCase());
const nativeValue = value => {
  const rem = value.match(/^([0-9.]+)rem$/);
  if (rem) return String(Number(rem[1]) * 16);
  const px = value.match(/^([0-9.]+)px$/);
  if (px) return String(Number(px[1]));
  const number = value.match(/^([0-9.]+)$/);
  if (number) return number[1];
  return JSON.stringify(value);
};
const groups = {
  colors: Object.entries(properties).filter(([name]) => name.startsWith('color-')),
  spacing: Object.entries(properties).filter(([name]) => name.startsWith('space-')),
  radii: Object.entries(properties).filter(([name]) => name.startsWith('radius-')),
  typography: Object.entries(properties).filter(([name]) => name.startsWith('font-size-') || name.startsWith('weight-') || name.startsWith('line-')),
  controls: Object.entries(properties).filter(([name]) => name.startsWith('control-height-')),
};
const themeExpression = `Object.freeze({\n${Object.entries(groups).map(([group, values]) =>
    `  ${group}: Object.freeze({\n${values.map(([name, value]) => `    ${camel(name.replace(/^[^-]+-/, ''))}: ${nativeValue(value)},`).join('\n')}\n  }),`
  ).join('\n')}\n})`;
const native = `// Generated from src/agent-up.css by scripts/build.mjs. Do not edit.\nexport const agentUpTheme = ${themeExpression};\n`;
const commonJs = `// Generated from src/agent-up.css by scripts/build.mjs. Do not edit.\nmodule.exports = { agentUpTheme: ${themeExpression} };\n`;
const declarations = `// Generated from src/agent-up.css. Do not edit.\nexport declare const agentUpTheme: {\n  readonly colors: Readonly<Record<string, string>>;\n  readonly spacing: Readonly<Record<string, number>>;\n  readonly radii: Readonly<Record<string, number>>;\n  readonly typography: Readonly<Record<string, string | number>>;\n  readonly controls: Readonly<Record<string, number>>;\n};\n`;

const avaloniaColors = groups.colors.map(([name, value]) => {
  const key = `AgentUp${name.split('-').map(part => part[0].toUpperCase() + part.slice(1)).join('')}`;
  const cssRgbaHex = value.match(/^#([0-9a-f]{6})([0-9a-f]{2})$/i);
  const normalized = value === 'rgba(0, 0, 0, 0.72)'
    ? '#B8000000'
    : cssRgbaHex ? `#${cssRgbaHex[2]}${cssRgbaHex[1]}` : value;
  return `  <Color x:Key="${key}">${normalized}</Color>\n  <SolidColorBrush x:Key="${key}Brush" Color="{StaticResource ${key}}"/>`;
}).join('\n');
const avaloniaMetrics = [
  ...groups.spacing.map(([name, value]) => [`AgentUp${name.split('-').map(x => x[0].toUpperCase() + x.slice(1)).join('')}`, nativeValue(value)]),
  ...groups.radii.filter(([, value]) => !value.includes('999')).map(([name, value]) => [`AgentUp${name.split('-').map(x => x[0].toUpperCase() + x.slice(1)).join('')}`, nativeValue(value)]),
];
const avalonia = `<ResourceDictionary xmlns="https://github.com/avaloniaui" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">\n` +
  `  <!-- Generated from src/agent-up.css by scripts/build.mjs. Do not edit. -->\n${avaloniaColors}\n` +
  `${avaloniaMetrics.map(([key, value]) => `  <x:Double x:Key="${key}">${value}</x:Double>`).join('\n')}\n</ResourceDictionary>\n`;
const dotnet = `// <auto-generated />\n// Generated from src/agent-up.css by scripts/build.mjs. Do not edit.\nnamespace AgentUp.Desktop.Shared.Models;\n\ninternal static class AgentUpThemeColors\n{\n${groups.colors.map(([name, value]) => `    internal const string ${name.replace(/^color-/, '').split('-').map(part => part[0].toUpperCase() + part.slice(1)).join('')} = "${value}";`).join('\n')}\n}\n`;

const outputs = new Map([
  ['dist/web/agent-up.css', css],
  ['dist/web/marketing.css', marketing],
  ['dist/web/tokens.cjs', commonJs],
  ['dist/native/index.js', native],
  ['dist/native/index.d.ts', declarations],
  ['dist/avalonia/AgentUpTheme.axaml', avalonia],
  ['dist/dotnet/AgentUpThemeColors.g.cs', dotnet],
]);

for (const [relative, content] of outputs) {
  const path = resolve(root, relative);
  if (check) {
    let current = '';
    try { current = await readFile(path, 'utf8'); } catch { /* Report the missing output below. */ }
    if (current !== content) throw new Error(`${relative} is stale. Run npm run build in AgentUp.DesignSystem.`);
  } else {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, content);
  }
}
