import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { emitCSharpColors, emitStyles, emitThemeResources } from './lib/avalonia.mjs';
import { catalogIndex, parseCatalog } from './lib/catalog.mjs';
import { parseCustomProperties, parseRules } from './lib/css.mjs';
import { emitNative } from './lib/native.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const src = resolve(root, 'src');
const check = process.argv.includes('--check');
const primitives = await readFile(resolve(src, 'agent-up.css'), 'utf8');
const product = await readProductCss(src);
const marketing = await readFile(resolve(src, 'marketing.css'), 'utf8');
const docs = await readFile(resolve(src, 'docs.css'), 'utf8');
const catalogHtml = await readCatalogHtml(src);
const css = `${primitives.trim()}\n\n${product.trim()}\n`;
const tokens = parseCustomProperties(primitives);
const required = [
  'color-canvas', 'color-surface', 'color-border-subtle', 'color-text-primary',
  'color-accent', 'color-status-healthy', 'color-status-danger', 'color-focus',
  'space-1', 'space-4', 'radius-md', 'control-height', 'font-size-sm',
];
for (const name of required) {
  if (!tokens[name]) throw new Error(`Missing canonical CSS property --au-${name}.`);
}

const catalog = parseCatalog(catalogHtml);
if (catalog.surfaces.length < 8) throw new Error('Design catalog is missing required product surfaces.');
const rules = parseRules(`${css}\n${marketing}`);
const index = catalogIndex(catalog);
const native = emitNative(tokens, rules);
const { grammars } = await import(resolve(src, 'syntax/highlight.mjs'));
const highlightSource = await readFile(resolve(src, 'syntax/highlight.mjs'), 'utf8');
const highlightTypes = await readFile(resolve(src, 'syntax/highlight.d.ts'), 'utf8');
const wrappedCatalog = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Agent-Up design catalog</title>
  <link rel="stylesheet" href="./agent-up.css" />
  <link rel="stylesheet" href="./marketing.css" />
  <link rel="stylesheet" href="./docs.css" />
</head>
${catalogHtml.slice(catalogHtml.indexOf('<body'))}
`;

const outputs = new Map([
  ['dist/web/agent-up.css', css],
  ['dist/web/marketing.css', marketing],
  ['dist/web/docs.css', docs],
  ['dist/web/catalog.html', wrappedCatalog],
  ['dist/web/catalog.json', `${JSON.stringify(catalog, null, 2)}\n`],
  ['dist/web/tokens.cjs', native.cjs],
  ['dist/native/index.js', native.js],
  ['dist/native/index.d.ts', native.dts],
  ['dist/avalonia/AgentUpTheme.axaml', emitThemeResources(tokens)],
  ['dist/avalonia/AgentUpStyles.axaml', emitStyles(rules, tokens, index)],
  ['dist/dotnet/AgentUpThemeColors.g.cs', emitCSharpColors(tokens)],
  ['dist/web/syntax/highlight.js', highlightSource],
  ['dist/web/syntax/highlight.d.ts', highlightTypes],
  ['dist/web/syntax/grammars.json', `${JSON.stringify(grammars, null, 2)}\n`],
  ['dist/dotnet/AgentUpSyntaxGrammars.g.cs', emitSyntaxGrammars(grammars)],
]);

for (const [relative, content] of outputs) {
  const path = resolve(root, relative);
  if (check) {
    let current = '';
    try { current = await readFile(path, 'utf8'); } catch { /* Report the missing output below. */ }
    if (current !== content) throw new Error(`${relative} is stale. Run npm run build in AgentUp.DesignSystem.`);
  } else {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, content);
  }
}

async function readCatalogHtml(directory) {
  const main = await readFile(resolve(directory, 'catalog.html'), 'utf8');
  const extras = (await readdir(directory))
    .filter(name => name.startsWith('catalog-') && name.endsWith('.html'))
    .sort();
  if (!extras.length) return main;
  const fragments = await Promise.all(extras.map(name => readFile(resolve(directory, name), 'utf8')));
  const close = main.lastIndexOf('</body>');
  return `${main.slice(0, close)}\n${fragments.join('\n')}\n${main.slice(close)}`;
}

function emitSyntaxGrammars(value) {
  return `// <auto-generated />
// Generated from src/syntax/highlight.mjs by scripts/build.mjs. Do not edit.
namespace AgentUp.Desktop.Shared.Models;

internal static class AgentUpSyntaxGrammars
{
    internal const string Json = """
${JSON.stringify(value, null, 2)}
""";
}
`;
}

async function readProductCss(directory) {
  const product = await readFile(resolve(directory, 'product.css'), 'utf8');
  const extras = (await readdir(directory))
    .filter(name => name.endsWith('.css') && !['agent-up.css', 'product.css', 'marketing.css', 'docs.css'].includes(name))
    .sort();
  if (!extras.length) return product;
  const fragments = await Promise.all(extras.map(name => readFile(resolve(directory, name), 'utf8')));
  return `${product}\n\n${fragments.join('\n\n')}`;
}
