<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\LocalInstaller.Sample.Shared\SampleProduct.cs" Link="SampleProduct.cs" />
    <ProjectReference Include="..\LocalInstaller.App\LocalInstaller.App.csproj" />
    <ProjectReference Include="..\LocalInstaller.Core\LocalInstaller.Core.csproj" />
  </ItemGroup>

</Project>
