const { withDangerousMod } = require('expo/config-plugins');
const fs = require('node:fs');
const path = require('node:path');

/**
 * Gives the androidTest APK a manifest that says these activities are not exported.
 *
 * androidx.test's InstrumentationActivityInvoker declares three activities with intent filters and
 * no android:exported. Anything targeting Android 12 or higher must state it explicitly, so the
 * merge fails and the test APK is never assembled:
 *
 *   android:exported needs to be explicitly specified for element
 *   <activity#androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity>
 *
 * The androidTest source set's manifest is the highest-priority one for that APK, so stating it
 * here settles the merge whatever version of androidx.test ends up resolved - which matters
 * because the version arrives transitively through Detox and is not ours to pin. They are
 * internal scaffolding for the instrumentation runner and nothing outside the test APK should be
 * able to start them, so false is both the safe answer and the correct one.
 */
const MANIFEST = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withDetoxAndroidTestManifest.js. Do not edit: prebuild rewrites it. -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">
  <application>
    <activity
        android:name="androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity"
        android:exported="false"
        tools:replace="android:exported" />
    <activity
        android:name="androidx.test.core.app.InstrumentationActivityInvoker$EmptyActivity"
        android:exported="false"
        tools:replace="android:exported" />
    <activity
        android:name="androidx.test.core.app.InstrumentationActivityInvoker$EmptyFloatingActivity"
        android:exported="false"
        tools:replace="android:exported" />
  </application>
</manifest>
`;

module.exports = function withDetoxAndroidTestManifest(config) {
  return withDangerousMod(config, [
    'android',
    async modConfig => {
      const directory = path.join(modConfig.modRequest.platformProjectRoot, 'app', 'src', 'androidTest');
      await fs.promises.mkdir(directory, { recursive: true });
      await fs.promises.writeFile(path.join(directory, 'AndroidManifest.xml'), MANIFEST, 'utf8');
      return modConfig;
    },
  ]);
};
