const fs = require('node:fs');
const path = require('node:path');

/**
 * The native E2E harness talks to Server and identity-provider processes on the CI host over
 * ephemeral HTTP ports. Production clients retain their normal transport policy; this exception
 * belongs only to the disposable harness app.
 *
 * usesCleartextTraffic alone is not enough on API 28+: a generated networkSecurityConfig that
 * forbids cleartext wins, and the emulator never sends a byte to 10.0.2.2.
 */
const ANDROID_CLEARTEXT_NETWORK_SECURITY_CONFIG = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withLocalHttpTransport.js. Do not edit: prebuild rewrites it. -->
<network-security-config>
  <base-config cleartextTrafficPermitted="true">
    <trust-anchors>
      <certificates src="system" />
    </trust-anchors>
  </base-config>
  <domain-config cleartextTrafficPermitted="true">
    <domain includeSubdomains="true">10.0.2.2</domain>
    <domain includeSubdomains="true">localhost</domain>
    <domain includeSubdomains="true">127.0.0.1</domain>
  </domain-config>
</network-security-config>
`;

function withLocalHttpTransport(config) {
  const { withAndroidManifest, withInfoPlist, withDangerousMod } = require('expo/config-plugins');
  config = withAndroidManifest(config, androidConfig => {
    allowAndroidCleartext(androidConfig.modResults);
    return androidConfig;
  });

  config = withDangerousMod(config, [
    'android',
    async androidConfig => {
      writeAndroidCleartextNetworkSecurityConfig(androidConfig.modRequest.platformProjectRoot);
      return androidConfig;
    },
  ]);

  return withInfoPlist(config, iosConfig => {
    allowIosLocalHttp(iosConfig.modResults);
    return iosConfig;
  });
}

function allowAndroidCleartext(manifest) {
  const application = manifest.manifest.application[0].$;
  application['android:usesCleartextTraffic'] = 'true';
  application['android:networkSecurityConfig'] = '@xml/network_security_config';
}

function writeAndroidCleartextNetworkSecurityConfig(platformProjectRoot) {
  const directory = path.join(platformProjectRoot, 'app', 'src', 'main', 'res', 'xml');
  fs.mkdirSync(directory, { recursive: true });
  const dest = path.join(directory, 'network_security_config.xml');
  fs.writeFileSync(dest, ANDROID_CLEARTEXT_NETWORK_SECURITY_CONFIG, 'utf8');
  return dest;
}

function allowIosLocalHttp(infoPlist) {
  infoPlist.NSAppTransportSecurity = {
    ...(infoPlist.NSAppTransportSecurity ?? {}),
    NSAllowsArbitraryLoads: true,
    NSAllowsLocalNetworking: true,
  };
}

module.exports = withLocalHttpTransport;
module.exports.allowAndroidCleartext = allowAndroidCleartext;
module.exports.allowIosLocalHttp = allowIosLocalHttp;
module.exports.ANDROID_CLEARTEXT_NETWORK_SECURITY_CONFIG = ANDROID_CLEARTEXT_NETWORK_SECURITY_CONFIG;
module.exports.writeAndroidCleartextNetworkSecurityConfig = writeAndroidCleartextNetworkSecurityConfig;
