<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <PackageId>LocalInstaller.Core</PackageId>
    <Version>$(LocalInstallerVersion)</Version>
  </PropertyGroup>

  <ItemGroup Condition="'$(ExcludeAgentUpProductConfiguration)' == 'true'">
    <Compile Remove="**/AgentUp*.cs" />
  </ItemGroup>

</Project>
