namespace AgentUp.Server.Features.Orchestration.Providers;

public static class AgentUpMcpGuidance
{
    public const string ServerInstructions =
        """
        Agent-Up is the registered MCP server for managing local AI-assisted development workspaces. Use these Agent-Up MCP tools whenever the user asks to use Agent-Up, agent up, the Agent-Up server, or the Agent-Up workspace manager.

        Treat phrases such as "deploy my app with Agent-Up", "run my app with Agent-Up", "start this workspace", "bring up the app", "serve this repo", or "open the app in Agent-Up" as requests to register or update the current repository/worktree from agent-up.json and call start_workspace with its absolute path immediately. Do not call list_workspaces or get_workspace_status before start_workspace for a known current repository/worktree. Agent-Up does not deploy to cloud infrastructure; it starts and manages the local development environment.

        Before using curl, shelling through the Agent-Up CLI, or starting application commands directly, prefer the MCP tools here when they can perform the requested Agent-Up operation. Use list_workspaces or get_workspace_status only when you need to choose among existing workspaces, inspect an already-running workspace, or answer an explicit status/list question. Use get_agent_up_context or get_agent_up_json_format when you need Agent-Up rules or configuration shape.

        Agent-Up validation is a feedback loop. After start_workspace, use the returned workspace id and allocated ports directly for browser MCP navigation. If browser navigation, inspection, waiting, screenshots, or interaction fails or times out, inspect the workspace console immediately through get_workspace_console on Orchestration MCP. If that tool is unavailable, query Audit MCP for recent application console events with kind=application and source=process for the workspace. Treat console output as the first diagnostic source; it often shows missing dependencies, failed commands, port binding errors, Docker startup failures, or build/runtime crashes. Fix the concrete console issue, then call start_workspace again and repeat the browser validation.

        Before starting a new coding task, call guard_commits for the current repository/worktree. If it fails, stop instead of making new changes unless the user explicitly asked to inspect, debug, or continue the existing queued or working-tree changes.

        At the end of every coding task, use enqueue_commit to declare each logical vertical-slice commit. Use enqueue_review_fix_commit when fixing pull request review feedback; each review-fix entry must represent exactly one review issue id. Do not run git add, git commit, or git stash directly. One enqueue call per logical slice; all files for a slice go in a single entry. Scope every conventional commit message to the queued slice, for example fix(Commits): validate queue metadata. Use the correct conventional commit prefix: feat means a user-facing addition, fix means a user-facing fix, test means test-only or smoke-validation changes, chore means maintenance/packaging/CI/tooling with no customer runtime effect, refactor means internal source changes with no behavior change, style means CSS/HTML only, and docs means documentation only including README and similar docs. If agent-up.json contains prompts.commitPolicy, follow that repository-specific policy when choosing prefixes and grouping commits. Cross-slice guidance or documentation updates must be queued in a separate guidance/docs entry instead of being bundled into an implementation slice. When feature-sliced paths are recognized, MCP rejects cross-slice file groups and mismatched slice labels. Mutating queue operations are blocked while Git has an active merge, rebase, cherry-pick, revert, or bisect. Use the commit queue MCP tools for queue inspection, metadata edits, file assignment, edit sessions, archive/restore, clear, and guard operations instead of shelling through commit CLI commands. enqueue_commit intentionally restores tracked files to their pre-change state after saving the patch; do not re-apply or modify those files after a successful enqueue because the queue owns them. After all enqueue calls, run get_commits_status so the developer can see the queue, then stop - the developer runs 'agentup commits next' to stage and commit each entry individually.
        """;
}
